# Generated by Django 6.0.3 on 2026-04-06 09:39

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ragione_sociale', models.CharField(max_length=255, verbose_name='Ragione Sociale')),
                ('partita_iva', encrypted_model_fields.fields.EncryptedCharField(verbose_name='Partita IVA')),
                ('sede_legale', models.TextField(verbose_name='Sede Legale')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data Creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data Aggiornamento')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_profiles', to='accounts.tenant', verbose_name='Tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
            ],
            options={
                'verbose_name': 'Profilo Aziendale',
                'verbose_name_plural': 'Profili Aziendali',
                'ordering': ['-created_at'],
            },
        ),
    ]
