# Generated by Django 6.0.3 on 2026-04-08 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/', verbose_name='File')),
                ('original_name', models.CharField(max_length=255, verbose_name='Nome Originale')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX')], max_length=10, verbose_name='Tipo File')),
                ('file_size', models.IntegerField(verbose_name='Dimensione (bytes)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data Upload')),
                ('status', models.CharField(choices=[('uploaded', 'Caricato'), ('parsed', 'Analizzato'), ('error', 'Errore')], default='uploaded', max_length=20, verbose_name='Stato')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documenti',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
