# Generated by Django 6.0.4 on 2026-04-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_parser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='parsed_content',
            field=models.TextField(blank=True, null=True, verbose_name='Contenuto Estratto'),
        ),
    ]
