# Generated by Django 6.0.3 on 2026-04-09 20:37

import apps.document_parser.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_parser', '0002_document_parsed_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=apps.document_parser.models.user_documents_path, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_size',
            field=models.PositiveIntegerField(verbose_name='Dimensione (bytes)'),
        ),
    ]
